### ISSUE TITLE
PieChart labels are incorrect

### ISSUE THREAD

**Issue by SidduSomething** [ramareddy12345/sample-app#1]
Small feedback 🙂

All labels on the Pie Chart are saying `Slice`. 
Actual labels like `Auto`, `Motorcycle`, ... are expected

![image](https://user-images.githubusercontent.com/8316961/141281244-54892ad5-bd11-47dd-8aca-c70bea43424f.png)

**Comment by ramareddy12345** [comment]
Thank you for reporting the issue. I have fixed typo. Please take latest
